#Sample devops secret. replace the variables with BASE64 encoded devops user and key
apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
type: Opaque
data:
  PING_IDENTITY_DEVOPS_USER: ${BASE64_ENCODED_PING_IDENTITY_DEVOPS_USER}
  PING_IDENTITY_DEVOPS_KEY: ${BASE64_ENCODED_PING_IDENTITY_DEVOPS_KEY}