apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate-admin
  labels:
    app: pingfederate
    tier: admin
spec:
  replicas: 1
  selector:
      matchLabels:
        app: pingfederate
        tier: admin
  template:
    metadata:
      labels:
        app: pingfederate
        tier: admin
    spec:
      containers:
      - name: console-node
        image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-alpine-edge
        ports:
        - containerPort: 9999
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
        envFrom:
          - configMapRef:
              name: console-variables
          - secretRef:
              name: devops-secret
              optional: true