---

# Section: chronograf service
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: tick
  name: chronograf
  labels:
    app: chronograf
    component: chronograf
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 3Gi