apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    component: influxdb
    app: influxdb
  name: influxdb-gp2
mountOptions:
- discard
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs