apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeteraddDeleteRate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jmeteraddDeleteRate
        company: PingIdentity
      name: jmeteraddDeleteRate
    spec:
      containers:
      - image: pingidentity/apache-jmeter:edge
        env: 
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory -JpdPort=389 -JaddDeleteRateThreadCount=1 -JaddDeleteRateDuration=1000 -JthreadCount=0 -Jduration=0
        imagePullPolicy: Always
        name: jmeteraddDeleteRate
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi