apiVersion: v1
data:
  SERVER_PROFILE_URL: https://github.com/ping-devops-program/anydevops
  SERVER_PROFILE_PATH: perf/profiles/jmeter
  # swap for with-errors
  # STARTUP_FOREGROUND_OPTS: --nongui -t /opt/out/instance/bin/ldap-witherrors.jmx -JpdHost=pingdirectory -JpdPort=389 -JsearchrateThreadCount=10 -JsearchrateDuration=1000 -JinvalidSearchrateThreadCount=10 -JinvalidSearchrateDuration=1000 -JthreadCount=0 -Jduration=0
  STARTUP_FOREGROUND_OPTS: --nongui -t /opt/out/instance/bin/ldap-witherrors.jmx -JpdHost=pingdirectory -JpdPort=389 -JthreadCount=10 -Jduration=1000
  # storing other options here:
  
  # --logfile result.txt
  #  -JapplicationName=jmeter-ldap -JtestName=pd-bind-search-mod 
  
  # TODO: this isnt working
  # -JupperUid=999999
  # MAX_HEAP_SIZE: 2g
kind: ConfigMap
metadata:
  name: jmeter-allrates
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-allrates
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jmeter-allrates
        company: PingIdentity
      name: jmeter-allrates
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: jmeter-allrates
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-allrates
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi