apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: see-everything
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users-see-everything
subjects:
- kind: Group
  name: users # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: see-everything
  apiGroup: rbac.authorization.k8s.io