apiVersion: v1
kind: Service
metadata:
  labels:
    app: influx-influxdb
    chart: influxdb-3.0.2
    heritage: Helm
    release: influx
  name: influxdb
  namespace: tick
spec:
  ports:
  - name: api
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: rpc
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: influxdb
  sessionAffinity: None
  type: ClusterIP