apiVersion: v1
data:
  SERVER_PROFILE_URL: https://github.com/ping-devops-program/anydevops
  SERVER_PROFILE_PATH: pf-rolling-update/profiles/jmeter
  STARTUP_FOREGROUND_OPTS: --nongui -t /opt/out/instance/bin/authorization_code.jmx
  # MAX_HEAP_SIZE: 2g
kind: ConfigMap
metadata:
  name: jmeter-variables