kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  role: pingdataconsole

configMapGenerator:
- name: pingdataconsole-environment-variables
  env: env_vars