version: "3"

services:
  jmeter:
    image: pingidentity/apache-jmeter:edge
    environment:
      - HEAP=2g
      - GIT_URL=https://github.com/ping-devops-program/anydevops.git
      - GIT_PATH=performance-testing/profiles/jmeter
      # 
      # - GIT_URL=https://github.com/ping-devops-program/anydevops
      # - GIT_PATH=pf-rolling-update/profiles/jmeter

    command: --nongui -t /opt/apache-jmeter/bin/results.jmx -Jreport_name=result1-useless -Jresults_dir=/opt/out -Jversion=1 -Jbuild=1 -Jconfiguration=1 -Jtester=samir -Jdescription=initial_test -Jkeywords=none -Jperformance_logs=okay
    # command: --nongui -t /opt/apache-jmeter/bin/authorization_code.jmx -JthreadCount=1 -Jduration=1 -JpfHost=pingfederate -JapplicationName=jmeter-pod
    # command: shell
    volumes:
      - /Users/samirgandhi/projects/anydevops/performance-testing/results:/opt/out