apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
  labels:
    app: pingfederate
    tier: engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingfederate
      tier: engine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pingfederate
        tier: engine
        version: "0.1"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: engine-variables
        - secretRef:
            name: devops-secret
            optional: true
        - configMapRef:
            name: jolokia-variables
        env:
          #this is what we will update with flux. new versions will be tags!
          - name: SERVER_PROFILE_ANYDEVOPS_BRANCH
            value: v1
        name: engine-node
        image: pingidentity/pingfederate:10.0.0-alpine-edge
        ports:
        - name: runtime
          containerPort: 9031
        readinessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 1
          initialDelaySeconds: 100
          failureThreshold: 1
        resources:
          requests:
            memory: 1.5Gi
            cpu: "1"
          limits:
            memory: 1.5Gi
            cpu: "1"
      # telegraf for monitoring PF engine jmx.       
      - name: telegraf
        image: docker.io/library/telegraf:1.9.5-alpine
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: telegraf-variables
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - mountPath: /etc/telegraf
          name: telegraf-conf
      volumes:
      - configMap:
          name: telegraf-conf
        name: telegraf-conf