apiVersion: v1
data:
  DATABASE: pingfed-tpc
  ENV: tpc
  MONITOR_HOST: http://influxdb.tick.svc.cluster.local:8086
  MONITOR_PASSWORD: root
  MONITOR_USERNAME: root
kind: ConfigMap
metadata:
  name: telegraf-variables