# FIXME: This is just a test cert that's meant to show how secrets can be
# created with certs and used by the nginx ingress controller. When we have
# CA-certs, put them here.
# FIXME: The private key is in the clear!!!

# NOTES:
#
# To generate a CSR (to be submitted to a CA) for ping.aws.com, follow these steps:
#
# 1. Generate the RSA private key:
#      openssl genrsa -out ping-aws.rsa 4096
#
# 2. Create a CSR to submit to CA:
#      openssl req -new -key ping-aws.rsa -out ping-aws.csr \
#        -reqexts SAN -extensions SAN -subj '/CN=ping-aws.com' \
#        -config <(cat /etc/ssl/openssl.cnf; printf "[SAN]\nsubjectAltName=DNS:*.ping-aws.com")
#
# 3. Obtain the CA-signed certificate and put it in ping-aws.crt
#
# ---
#
# For test purposes, create a key and a self-signed certificate in one step:
#
# 1. For test purposes, create a key and a self-signed certificate in one step:
#      openssl req -x509 -nodes -newkey rsa:2048 -days 3650 -sha256 \
#        -keyout ping-aws.key -out ping-aws.crt -subj '/CN=ping-aws.com' \
#        -reqexts SAN -extensions SAN \
#        -config <(cat /etc/ssl/openssl.cnf; printf "[SAN]\nsubjectAltName=DNS:*.ping-aws.com")
#
#    On Open SSL 1.1.1 or later, after creating the key, run this:
#      openssl req -sha256 -new -x509 -days 3650 \
#        -key ping-aws.rsa -out ping-aws.crt \
#        -subj /CN=ping-aws.com \
#        -addext "subjectAltName = DNS:*.ping-aws.com"
#
# ---
#
# To transform the RSA key (ping-aws.rsa) to PKCS#8 (ping-aws.key) format, run:
#   openssl pkcs8 -topk8 -inform PEM -outform PEM \
#     -in ping-aws.rsa -out ping-aws.key -nocrypt
#
# Copy the contents of ping-aws.crt and ping-aws.key into tls.crt and tls.key
# in the tls secret object below.

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-secret
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC+DCCAeCgAwIBAgIJAJdLpmvIONuYMA0GCSqGSIb3DQEBCwUAMCUxIzAhBgNV
    BAMMGmVrcy1wb2MuYXUxLnBpbmctbGFiLmNsb3VkMB4XDTE5MDkwNDIwNTk0OVoX
    DTI5MDkwMTIwNTk0OVowJTEjMCEGA1UEAwwaZWtzLXBvYy5hdTEucGluZy1sYWIu
    Y2xvdWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDATjdo71gI/HYE
    tFKTzqp19pG8F8WzSTtyNQ5cn8+hCx2uQZ3ep9LjwieTWd9xjRXtnO03o4Mc5Zez
    uUTJAlFmosLSQw+pdexJYkNMEri7D1wPRjztHG8Ei/uAyY7IL59qIB2efGU1a2Po
    h+2SrHQUZyRkFpnAtZ9ZxRE4AXagtwuFEPUxubr9bP177a5Cm3CdiDOn1bC78ntD
    BN/w/gaOvjVGjAjwRr7YjC9Hke6Nnlrbjiq5eUCCD5UXB0e2CP16tXljErAETQkB
    tYkEvwIL95SidDnbDqEMVsZJ8WERABUIFjkyN3mwWZcCFYaqewoORZs7/DJbeIN6
    EGpm3RnRAgMBAAGjKzApMCcGA1UdEQQgMB6CHCouZWtzLXBvYy5hdTEucGluZy1s
    YWIuY2xvdWQwDQYJKoZIhvcNAQELBQADggEBAAAZaHXi0A7HsMsMw338F5x7thos
    w+xrXRChc6u9Hj8sOXUoIFLDHOBAYakUlbmLqP6LItqcAFzp+wWx3dnZ+xvjB6eh
    MqwqNPsNF3+NOQSqZ6vvBf8UdY5MyPnxL5/QERY54oeitehw83G0YtY2eUGR6db9
    jSB6jNC0qhuLq/COHqvHtLOhcnfrDNJkGlVBYwu5dmH8UTULWeNUYH1+lFidDsCG
    9fBbmk0EdJKIDE1a18D5RBJi4cNawC77y2ch9ZNEqqECBBDAfUQy8IMPWzy5+GHm
    N5PgkG2+ndkxlPiTi24KT4RPXg+MhYzBQRXQu/virx5+mcYc9FH8BTU4ZcU=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDATjdo71gI/HYE
    tFKTzqp19pG8F8WzSTtyNQ5cn8+hCx2uQZ3ep9LjwieTWd9xjRXtnO03o4Mc5Zez
    uUTJAlFmosLSQw+pdexJYkNMEri7D1wPRjztHG8Ei/uAyY7IL59qIB2efGU1a2Po
    h+2SrHQUZyRkFpnAtZ9ZxRE4AXagtwuFEPUxubr9bP177a5Cm3CdiDOn1bC78ntD
    BN/w/gaOvjVGjAjwRr7YjC9Hke6Nnlrbjiq5eUCCD5UXB0e2CP16tXljErAETQkB
    tYkEvwIL95SidDnbDqEMVsZJ8WERABUIFjkyN3mwWZcCFYaqewoORZs7/DJbeIN6
    EGpm3RnRAgMBAAECggEATKfhFocxxIM+WCm5MQoUkOk0tpGTUSBD/gaALxPVJBDW
    R/wH/hVPz1I5jFcq5oyizRDczmzzerVaf12+uZGe+RawKjhpKdfD1IzC3rQnxwkc
    XUpWRv4qktlp67Bspge1uAwNQnu7rEuei7aDURBFRUzICM2phFPhrVsMvhJ3QyCC
    793mnYCJy/ZDvPqM5L2Zx46EZ8tnRDj+m3kfjtWnpJ6ea4DQzDbkceIUnpCZc9Yk
    CkrND59LU9HemUZlEGfFS+DJ2BYI325cPgPGIJ7epr/VCX9xwY8IHhEClJHt96qx
    qm/Dq3DnRsmf13qJsaCvkq8LAvgFwnYYQOSzE/xlQQKBgQDpGOkelCOqseQyeZ7X
    oOGbTQ27Jtf48XXDn697zr53lguo+4A7W4sboAF1dOAa40cpdfGs6D1t6cZtZ5WR
    9xIefXBMLlrybJ5qdR0fUNIgu8sPB2fsv5HVfwx3Q9sTUp6m4HPRyczvV+jF1BAH
    aThw2n98iKddiOGrtiL+GZslpQKBgQDTM0WGnnTy0EHPF84YS3dyaES7KA2uOvtg
    YSGe2jDp2T0fB0fj39a3enyhH0ZixZZDYmiPlt1n3kf0lHdo7iZwus9K1K9Dtmus
    Q8QT5S/gRzZm3JTzm/hAWafoCTfK9u+0bNftZK/QtVSRqzINqI/YZSMomQoI+GqZ
    69xLQF3jvQKBgDApYnlb+GabbN/0+xnodtTkvdKOew9HrKJnyxVUqUwCJ5SZqmwZ
    RQvHKqX/KRLFJP3vDalBLvgX1lTikyfemdLM7jf/V/FA+hZa7lJ7G3+B7bnEOPfU
    uSgYoRW/YnOCnZ8zPxr4jCxjyIefglRVrEC9FJxBi/sqfh5BesdvuPu1AoGBANHW
    TSu1YAin9dqmkjP9Nw5Kno88+mqzW3KkztyfeJ2/I0Ui3MCBczoUzqLfCfW0ztjg
    e3a+s/gxF1jf8cwlYbf7Q13b9s7V/iDHq5cAzRKObnTAkJWBz6NP8M1P60kTE5I1
    2kuZED3TC9U3PKHpahHcWpRJiXjkKDYJ63Qw3ZgZAoGADmZ8b/+XyQ8QyyIRUgpJ
    mu+pBXD/V0xzCZSjc0tPXfKJhAMl96aM8L25a3xtEorI+iv79YxX5cjWS31fs9Az
    yMnOStMT1CCFAK9NgrQd8QgATlho+CdbQ39/TKERMJskaym8dHeJHMdh/j7b+ZUb
    dVNIj646N1ovE+dxS/6JrGY=
    -----END PRIVATE KEY-----
