apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jmeter-openbanking
  namespace: perf-pingdirectory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-openbanking
      company: PingIdentity
  serviceName: jmeter-openbanking
  template:
    metadata:
      labels:
        app: jmeter-openbanking
        company: PingIdentity
    spec:
      nodeSelector:
        role: perf-clients
      # fixme when running multiple DGs
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: failure-domain.beta.kubernetes.io/zone
      #           operator: In
      #           values:
      #           - us-east-2b
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            # value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory.perf-pingdirectory -JpdPort=389 -JdgHost=pingdatagovernance.perf-pingdirectory -JdgPort=443 -JopenbankingThreadCount=3 -JopenbankingDuration=10000 -JthreadCount=0 -Jramp=0 -Jduration=0
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -Jjmeter.save.saveservice.response_data.on_error=true -l /opt/out/instance/results/errors.jtl -JpdHost=pingdirectory.perf-pingdirectory -JpdPort=389 -JdgHost=pingdatagovernance.perf-pingdirectory -JdgPort=443 -JopenbankingThreadCount=3 -JopenbankingDuration=10000 -JthreadCount=0 -Jramp=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 3600m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-openbanking
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi

---

