apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-searchrate-0
  namespace: perf-pingdirectory
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-searchrate
        company: PingIdentity
    spec:
      nodeSelector:
        role: soak
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory-0.pingdirectory.perf-pingdirectory -JpdPort=389 -JsearchrateThreadCount=1 -JsearchrateDuration=10000 -JthreadCount=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 1800m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-searchrate
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-searchrate-1
  namespace: perf-pingdirectory
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-searchrate
        company: PingIdentity
    spec:
      nodeSelector:
        role: soak
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory-1.pingdirectory.perf-pingdirectory -JpdPort=389 -JsearchrateThreadCount=1 -JsearchrateDuration=10000 -JthreadCount=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 1800m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-searchrate
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-searchrate-2
  namespace: perf-pingdirectory
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-searchrate
        company: PingIdentity
    spec:
      nodeSelector:
        role: soak
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory-2.pingdirectory.perf-pingdirectory -JpdPort=389 -JsearchrateThreadCount=1 -JsearchrateDuration=10000 -JthreadCount=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 1800m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-searchrate
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-modrateadmin-0
  namespace: perf-pingdirectory
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-modrateadmin
        company: PingIdentity
    spec:
      nodeSelector:
        role: soak
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory-0.pingdirectory.perf-pingdirectory -JpdPort=389 -JmodrateadminThreadCount=1 -JmodrateadminDuration=10000 -JthreadCount=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 1800m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-modrateadmin
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-modrateadmin-1
  namespace: perf-pingdirectory
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-modrateadmin
        company: PingIdentity
    spec:
      nodeSelector:
        role: soak
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory-1.pingdirectory.perf-pingdirectory -JpdPort=389 -JmodrateadminThreadCount=1 -JmodrateadminDuration=10000 -JthreadCount=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 1800m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-modrateadmin
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-modrateadmin-2
  namespace: perf-pingdirectory
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-modrateadmin
        company: PingIdentity
    spec:
      nodeSelector:
        role: soak
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: perf/profiles/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/ldap.jmx -JpdHost=pingdirectory-2.pingdirectory.perf-pingdirectory -JpdPort=389 -JmodrateadminThreadCount=1 -JmodrateadminDuration=10000 -JthreadCount=0 -Jduration=0
          - name: MAX_HEAP_SIZE
            value: 1800m
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter-modrateadmin
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 9270
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi

---

