apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory-gp2
mountOptions:
- discard
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory-io1
mountOptions:
- discard
parameters:
  fsType: ext4
  iopsPerGB: "50"
  type: io1
provisioner: kubernetes.io/aws-ebs
---
apiVersion: v1
data:
  ADMIN_USER_PASSWORD_FILE: /usr/local/secrets/admin-user-password
  LOCATION: Austin
  MAX_HEAP_SIZE: 4g
  ORCHESTRATION_TYPE: kubernetes
  PING_IDENTITY_DEVOPS_KEY: '@PING_IDENTITY_DEVOPS_KEY@'
  PING_IDENTITY_DEVOPS_USER: '@PING_IDENTITY_DEVOPS_USER@'
  ROOT_USER_PASSWORD_FILE: /usr/local/secrets/root-user-password
  SERVER_PROFILE_PATH: baseline/pingdirectory
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
  USER_BASE_DN: dc=example,dc=com
kind: ConfigMap
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory-environment-variables-764cc49ctb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory
spec:
  clusterIP: None
  ports:
  - name: ldap
    port: 389
  - name: ldaps
    port: 636
  selector:
    role: pingdirectory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    role: pingdirectory
  name: ds
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      role: pingdirectory
  serviceName: pingdirectory
  template:
    metadata:
      annotations:
        lastUpdateTime: NA
      labels:
        role: pingdirectory
    spec:
      containers:
      - env:
        - name: K8S_STATEFUL_SET_NAME
          value: ds
        - name: K8S_STATEFUL_SET_SERVICE_NAME
          value: pingdirectory
        - name: MAX_HEAP_SIZE
          value: 8g
        - name: UNBOUNDID_JAVA_ARGS
          value: -client -Xmx8g -Xms8g
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables-764cc49ctb
        image: pingidentity/pingdirectory:edge
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/staging/hooks/90-shutdown-sequence.sh
        livenessProbe:
          exec:
            command:
            - liveness.sh
          failureThreshold: 10
          initialDelaySeconds: 600
          periodSeconds: 30
        name: ds
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        readinessProbe:
          exec:
            command:
            - liveness.sh
          failureThreshold: 120
          periodSeconds: 30
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/out
          name: out-dir
      terminationGracePeriodSeconds: 300
      volumes:
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        role: pingdirectory
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: pingdirectory-gp2
